import os
import random
import sys
import time
from time import sleep
os.system('clear')
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.1)

mengetik('\033[32;1mTERIMA KASIH SUDAH MENGGUNAKAN TOOLS KAMI')
mengetik('\033[32;1mMESSAGE :INSTALL BAHAN TERLEBIH DAHULU')
mengetik('\033[32;1mJIKA ADA ERROR DALAM TOOLS INI,SEGERA HUBUNGI ADMIN')
mengetik('\033[32;1MSELAMAT BERAKSI,,SEMOGA HARIMU MENYENANGKAN :)')
time.sleep(1)
mengetik('\033[32;1mGOOD LUCK...')
print ('')
mengetik('\033[32;1mPLEASE WAIT...')
time.sleep(1)
mengetik('\033[1;36m[ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ] 100%')
sleep(0.1)
os.system('clear')
print ('\033[31;1m███╗   ███╗██████╗    ██╗███╗   ██╗ ██████╗ ███████╗███████╗')
sleep(0.1)
print ('\033[31;1m████╗ ████║██╔══██╗   ██║████╗  ██║██╔════╝ ██╔════╝██╔════╝')
sleep(0.1)
print ('\033[31;1m██╔████╔██║██████╔╝   ██║██╔██╗ ██║██║  ███╗███████╗███████╗')
sleep(0.1)
print ('\033[37;1m██║╚██╔╝██║██╔══██╗   ██║██║╚██╗██║██║   ██║╚════██║╚════██║')
sleep(0.1)
print ('\033[37;1m██║ ╚═╝ ██║██║  ██║██╗██║██║ ╚████║╚██████╔╝███████║███████║')
sleep(0.1)
print ('\033[37;1m╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝╚══════╝')
print ('\033[33;1m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬')
print ('')
mengetik('\033[33;1m          [ + ]         Author : Mr.IngsS')
mengetik('\033[33;1m          [ + ]      OFFICIAL BLACK CYBER TEAM')
mengetik('\033[33;1m          [ + ]  Contact me : [ boslinux@gmail.com ]')
print ('')
print ('\033[33;1m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬')
print ('')
time.sleep(1)
print ('\033[33;1m╔══════════════════════════════════════════════════════════════════════════╗')
print ('\033[33;1m║                          [ MENU TOOLS HACKING ]                          ║')
print ('\033[33;1m║                                                                          ║')
print ('\033[33;1m║════════════════════════════════════╦═════════════════════════════════════║')
print ('\033[36;1m║ [ 1 ].RANSOMWARE CREATOR           ║            CATATAN TOOLS            ║')
print ('\033[36;1m║ [ 2 ].VIRUS APP CREATOR            ║_____________________________________║')
print ('\033[36;1m║ [ 3 ].VIRUS DROID CREATOR          ║ TOOLS INI AKAN UPDATE SETIAP BULAN  ║')
print ('\033[36;1m║ [ 4 ].SQLI SCANNING                ║ JIKA ADA ERROR/TIDAK DI PAHAMI.     ║')
print ('\033[36;1m║ [ 5 ].SPAM-CALL                    ║ SEGERA HUBUNGI ADMIN.               ║')
print ('\033[36;1m║ [ 6 ].SPAM-WHATSAPP                ║_____________________________________║')
print ('\033[36;1m║ [ 7 ].VENOM INJECTION              ║ DILARANG KERAS MERECORD TOOLS INI.  ║')
print ('\033[36;1m║ [ 8 ].SAYDOG FRAMEWORK             ║ TANPA IZIN ADMIN [ MR.INGSS ].      ║')
print ('\033[36;1m║ [ 9 ].BRUTEFORCE-FACEBOOK          ║ DAN DILARANG MENJUAL BELIKAN NYA.   ║')
print ('\033[36;1m║ [ 10 ].BRUTEFORCE-INSTAGRAM        ║_____________________________________║')
print ('\033[36;1m║ [ 11 ].TERMUX-THEME                ║ GUNAKAN TOOLS INI DENGAN BIJAK.     ║')
print ('\033[36;1m║ [ 12 ].TROJAN-CREATOR              ║ KARNA KAMI TIDAK BERTANGGUNG JAWAB  ║')
print ('\033[36;1m║ [ 13 ].METASPLOIT-HELPER           ║ ATAS AKSI PERETASAN ANDA            ║')
print ('\033[36;1[║ [ 14 ].INSTALLING-BAHAN            ║                                     ║')
print ('\033[36;1m║ [ 15 ].EXIT/CLOSE                  ║                                     ║')
print ('\033[36;1m╚════════════════════════════════════╩═════════════════════════════════════╝')
time.sleep(1)
pilih = input ('[ + ] PILIH TOOLS : ')
if pilih == "1":
        os.system('clear')
        os.system('git clone https://github.com/saydog/Ransomware-creator')
        mengetik('\033[1;33mINSTALLING RANSOMWARE-CREATOR SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd Ransomware-creator ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python ransom.py ]')
elif pilih == "2":
        os.system('clear')
        os.system('git clone https://github.com/BlackCyberAnonim/B-VIRUS')
        mengetik('\033[1;33mINSTALLING VIRUS APP CREATOR SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd B-VIRUS ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python2 B-VIRUS.py ]')
elif pilih == "3":
        os.system('clear')
        os.system('git clone https://github.com/saydog/Virus-droid-creator')
        mengetik('\033[1;33mINSTALLING VIRUS-DROID-CREATOR SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd Virus-droid-creator ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python2 dog.py ]')
elif pilih == "4":
        os.system('clear')
        os.system('git clone https://github.com/anonkyuhuu/sqli-checker')
        mengetik('\033[1;33nINSTALLING SPAM-CALL SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd sqli-checker ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd data ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python3 main.py ]')
elif pilih == "5":
        os.system('clear')
        os.system('git clone https://github..com/sandiwijayani1/SpamCall-1')
        mengetik('\033[1;33mINSTALLING SPAMCALL SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd SpamCall-1 ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python SpamCall.py ]')
elif pilih == "6":
        os.system('clear')
        os.system('git clone https://github.com/sandiwijayani1/SpamWa')
        mengetik('\033[1;33mINSTALLING SPAM-WHATSAPP SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd SpamWa ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python3 spam.py ]')
elif pilih == "7":
        os.system('clear')
        os.system('git clone https://github.com/saydog/Venom-injection-tool')
        mengetik('\033[1;33mINSTALLING VENOM-INJECTION SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd Venom-injection-tool ]')
        menegtik('\033[37;1mSELANJUTNYA KETIKAN [ python2 dog.py ]')
elif pilih == "8":
        os.system('clear')
        os.system('git clone https://github.com/saydog/saydog-framework')
        menegetik('\033[1;33mINSTALLING SAYDOG-FRAMEWORK SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd saydog-framework ]')
        menegtik('\033[37;1mSELANJUTNYA KETIKAN [ chmod +x install ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ ./install ]')
elif pilih == "9":
        os.system('clear')
        os.system('git clone https://github.com/Din-zUgex95/FBbruT')
        mengetik('\033[1;33mINSTALLING BRUTEFORCE FACEBOOK SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd FBbruT ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ nano pass.txt ]')
        mengetik('\033[37;1mSILAHKAM EDIT TERLEBIH DAHULU WORDLIST NYA')
        mengetik('\033[36:1mLALU KETIKAN [ python2 brute-FB.py ]')
        mengetik('\033[37;1mJIKA TIDAK PAHAM SILAHKAN HUBUNGI ADMIN')
elif pilih == "10":
        os.system('clear')
        os.system('git clone https://github.com/saydog/HEK-IG')
        mengetik('\033[1;33mINSTALLING BRUTEFORCE INSTAGRAM SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd HEK-IG ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python2 dog.py ]')
elif pilih == "11":
        os.system('clear')
        os.system('git clone https://github.com/saydog/termux-theme')
        mengetik('\033[1;33mINSTALLING TERMUX-THEME SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd termux-theme ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ sh install.sh ]')
elif pilih == "12":
        os.system('clear')
        os.system('git clone https://github.com/saydog/Trojan-creator')
        mengetik('\033[1;33mINSTALLING TROJAN-CREATOR SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd Trojan-creator ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ python2 trojan.py ]')
elif pilih == "13":
        os.system('clear')
        os.system('git clone https://github.com/saydog/Metasploit-Helper')
        mengetik('\033[1;33mINSTALLING METASPLOIT-HELPER SUCCESS')
        time.sleep(1)
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ cd Metasploit-Helper ]')
        mengetik('\033[37;1mSELANJUTNYA KETIKAN [ sh install.sh ]')
elif pilih == "14":
        os.system('clear')
        mengetik('\033[1;33mINSTALLING BAHAN TOOLS')
        time.sleep(1)
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install nano')
        os.system('pkg install python')
        os.system('pkg install python2')
        os.systen('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('pip2 install tqdm')
        os.system('pip2 install colorama')
        os.system('pip2 install bs4')
        os.system('pip2 install uncompyle6')
        os.system('pkg install curl')
        os.system('pkg install wget')
        os.systen('pkg install jq')
        time.sleep(1)
        mengetik('\033[1;33mINSTALLING BAHAN-TOOLS SUCCESS')
        mengetik('\033[1;33mSILAHKAN KETIK [ python ings204.py ]')
elif pilih == "15":
        os.system('clear')
        mengetik('\033[32;1mEXITING PROGRAM')
        os.system('exit')